---
new_page_extension: md
auto_deploy: false
admin_path: "/public/login"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/search
  label: Search
  create: all
  match: "**/*"
- type: directory
  path: content/webpages
  label: Webpages
  create: all
  match: "**/*"
upload_dir: static/wp-image
public_path: "/wp-image"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:, :year:, :month:, :day:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.88.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.78.2
